<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_get_clip</name>
   <tag></tag>
   <elementGuidId>9332a80d-3506-4b62-98d4-61b43406f3e1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//button[@class='ek-primary-button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//button[@class='ek-primary-button']</value>
      <webElementGuid>a124248e-076c-4cfe-9237-293ab6be34e8</webElementGuid>
   </webElementProperties>
</WebElementEntity>
