<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_new_username</name>
   <tag></tag>
   <elementGuidId>753abec7-cf27-437f-b7bc-7de607c39d07</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@name='Name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@name='Name']</value>
      <webElementGuid>dccf57e1-27f8-4760-b25f-cf2564c6b8c7</webElementGuid>
   </webElementProperties>
</WebElementEntity>
